# Generated by Django 2.1 on 2018-08-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decentmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='total',
        ),
        migrations.AddField(
            model_name='assignment',
            name='total',
            field=models.IntegerField(default=-1),
        ),
    ]
